### ISSUE TITLE
Only two years data back is showed

### ISSUE THREAD

**Issue by AlbertoMCS** [SeBassTian23/CalendarHeatmap#13]
Hi, 
Thanks for the plugging, really useful. 
When trying to load data bigger than 2 years (let us say 3-4 years) just the last two years or less are loaded, see example below:
Data: data from 2012 to 2015 (below just a subset of the data as the list is too long):
`oblist = [{"count":100,"date":"2012-01-01"},{"count":100,"date":"2012-01-02"},{"count":100,"date":"2012-01-03"},{"count":100,"date":"2012-01-04"},{"count":100,"date":"2012-01-05"},{"count":100,"date":"2012-01-06"},{"count":100,"date":"2012-01-07"},..., ,{"count":100,"date":"2015-12-01"}];`

`$("#calendar2011").CalendarHeatmap(oblist, {
                            months: 50,
                            coloring:"custom",
//                            weekStartDay: 1,
                            lastMonth:12,
                            lastYear:2015,
                            labels: {
                                days: false,
                                months: true,
                                custom: {
                                    weekDayLabels: null,
                                    monthLabels: 'MMM-YY'
                                }
                            },
                            tiles: {
                                shape:"square"
                                }
                        });`

This is what I get: 

![image](https://user-images.githubusercontent.com/16774169/131232124-8ed06172-a655-4333-a8e8-4ddc910948c0.png)

As you can see data before Jan-14 is not showed. 
I tested with diferent data and always got the same behaviour.
Thanks,
Alberto.

**Comment by SeBassTian23** [comment]
Hi Alberto,

I'm glad you find the plugin useful thanks for reporting the issue. I will take a look and see if I can fix the issue within the next couple of days. Please let me know if you can narrow down the issue.

Best
Sebastian

**Comment by AlbertoMCS** [comment]
Hi Sebastian, 
Thanks for your quick response. 
I workaround the issue by adding each year separately rather than all together (see below). It worked, so I am happpy with the result, so it is up to you if you want to either fix or close the ticket.
Many thanks!
Alberto.

`$("#calendar2011").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2011, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });
$("#calendar2012").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2012, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });
$("#calendar2013").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2013, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });
$("#calendar2014").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2014, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });
$("#calendar2015").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2015, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });
$("#calendar2016").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2016, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });
$("#calendar2017").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2017, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });
$("#calendar2018").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2018, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });
$("#calendar2019").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2019, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });
$("#calendar2020").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2020, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });
$("#calendar2021").CalendarHeatmap(oblist, { months: 12, coloring:"custom", // weekStartDay: 1, lastMonth:12, lastYear:2021, labels: { days: false, months: true, custom: { weekDayLabels: null, monthLabels: 'MMM-YY' } }, tiles: { shape:"square" } });`

![image](https://user-images.githubusercontent.com/16774169/131400867-59f9ac3d-5643-4caf-8d15-64942ca36d4f.png)

**Comment by SeBassTian23** [comment]
I'm glad you found a solution that works for you, but I will definitely look into why it is not working properly.

I will keep you posted

**Comment by SeBassTian23** [comment]
OK,

I published a new release that should take care of the issue. Please note, that moment.js is also no longer required. Please let me know if it works for you.

Best

**Comment by AlbertoMCS** [comment]
Hi Sebastian, 
Thanks for your updated, unfortunately still does not work (I used the css and js files from dist folder). Find below the code if you want to reproduce:
`         $(document).on("click","#workship",function(){
            $("#calendar2021").CalendarHeatmap(ob1, {
                            months: 40,
                            coloring:"custom",
                            lastMonth:12,
                            lastYear:2014,
                            legend:false,
                            legend: {
                                show: true,
                                align: "right",
                                minLabel: "No Data",
                                maxLabel: "Full Data",
                                divider: " to "
                            },
                            labels: {
                                days: false,
                                months: true,
                                custom: {
                                    weekDayLabels: null,
                                    monthLabels: 'MMM-YY'
                                }
                            },
                            tiles: {
                                shape:"square"
                                },
//                            tooltips: {
//                                show: true,
//                                options: {}
//                            }
                        }); 
             $('#dlgModalTraCountWebtris').show();
         });`

The data:
`ob1 = [{count:100,date:"2012-01-01"},{count:100,date:"2012-01-02"},{count:100,date:"2012-01-03"},{count:100,date:"2012-01-04"},{count:100,date:"2012-01-05"},{count:100,date:"2012-01-06"},{count:100,date:"2012-01-07"},{count:100,date:"2012-01-08"},{count:100,date:"2012-01-09"},{count:100,date:"2012-01-10"},{count:100,date:"2012-01-11"},{count:100,date:"2012-01-12"},{count:100,date:"2012-01-13"},{count:100,date:"2012-01-14"},{count:100,date:"2012-01-15"},{count:100,date:"2012-01-16"},{count:100,date:"2012-01-17"},{count:100,date:"2012-01-18"},{count:100,date:"2012-01-19"},{count:100,date:"2012-01-20"},{count:100,date:"2012-01-21"},{count:100,date:"2012-01-22"},{count:100,date:"2012-01-23"},{count:100,date:"2012-01-24"},{count:100,date:"2012-01-25"},{count:100,date:"2012-01-26"},{count:100,date:"2012-01-27"},{count:100,date:"2012-01-28"},{count:100,date:"2012-01-29"},{count:100,date:"2012-01-30"},{count:100,date:"2012-01-31"},{count:100,date:"2012-02-01"},{count:100,date:"2012-02-02"},{count:100,date:"2012-02-03"},{count:100,date:"2012-02-04"},{count:100,date:"2012-02-05"},{count:100,date:"2012-02-06"},{count:100,date:"2012-02-07"},{count:100,date:"2012-02-08"},{count:100,date:"2012-02-09"},{count:100,date:"2012-02-10"},{count:100,date:"2012-02-11"},{count:100,date:"2012-02-12"},{count:100,date:"2012-02-13"},{count:100,date:"2012-02-14"},{count:100,date:"2012-02-15"},{count:100,date:"2012-02-16"},{count:100,date:"2012-02-17"},{count:100,date:"2012-02-18"},{count:100,date:"2012-02-19"},{count:100,date:"2012-02-20"},{count:100,date:"2012-02-21"},{count:100,date:"2012-02-22"},{count:100,date:"2012-02-23"},{count:100,date:"2012-02-24"},{count:100,date:"2012-02-25"},{count:100,date:"2012-02-26"},{count:100,date:"2012-02-27"},{count:100,date:"2012-02-28"},{count:100,date:"2012-02-29"},{count:100,date:"2012-03-01"},{count:100,date:"2012-03-02"},{count:100,date:"2012-03-03"},{count:100,date:"2012-03-04"},{count:100,date:"2012-03-05"},{count:100,date:"2012-03-06"},{count:100,date:"2012-03-07"},{count:100,date:"2012-03-08"},{count:100,date:"2012-03-09"},{count:100,date:"2012-03-10"},{count:100,date:"2012-03-11"},{count:100,date:"2012-03-12"},{count:100,date:"2012-03-13"},{count:100,date:"2012-03-14"},{count:100,date:"2012-03-15"},{count:100,date:"2012-03-16"},{count:100,date:"2012-03-17"},{count:100,date:"2012-03-18"},{count:100,date:"2012-03-19"},{count:100,date:"2012-03-20"},{count:100,date:"2012-03-21"},{count:100,date:"2012-03-22"},{count:100,date:"2012-03-23"},{count:100,date:"2012-03-24"},{count:96,date:"2012-03-25"},{count:100,date:"2012-03-26"},{count:100,date:"2012-03-27"},{count:100,date:"2012-03-28"},{count:100,date:"2012-03-29"},{count:100,date:"2012-03-30"},{count:100,date:"2012-03-31"},{count:100,date:"2012-04-01"},{count:100,date:"2012-04-02"},{count:100,date:"2012-04-03"},{count:100,date:"2012-04-04"},{count:100,date:"2012-04-05"},{count:100,date:"2012-04-06"},{count:100,date:"2012-04-07"},{count:100,date:"2012-04-08"},{count:100,date:"2012-04-09"},{count:100,date:"2012-04-10"},{count:100,date:"2012-04-11"},{count:100,date:"2012-04-12"},{count:100,date:"2012-04-13"},{count:100,date:"2012-04-14"},{count:100,date:"2012-04-15"},{count:100,date:"2012-04-16"},{count:100,date:"2012-04-17"},{count:100,date:"2012-04-18"},{count:100,date:"2012-04-19"},{count:100,date:"2012-04-20"},{count:4,date:"2012-04-21"},{count:96,date:"2012-04-22"},{count:100,date:"2012-04-23"},{count:100,date:"2012-04-24"},{count:100,date:"2012-04-25"},{count:100,date:"2012-04-26"},{count:100,date:"2012-04-27"},{count:100,date:"2012-04-28"},{count:100,date:"2012-04-29"},{count:100,date:"2012-04-30"},{count:100,date:"2012-05-01"},{count:100,date:"2012-05-02"},{count:100,date:"2012-05-03"},{count:100,date:"2012-05-04"},{count:100,date:"2012-05-05"},{count:100,date:"2012-05-06"},{count:100,date:"2012-05-07"},{count:100,date:"2012-05-08"},{count:100,date:"2012-05-09"},{count:100,date:"2012-05-10"},{count:100,date:"2012-05-11"},{count:100,date:"2012-05-12"},{count:100,date:"2012-05-13"},{count:100,date:"2012-05-14"},{count:100,date:"2012-05-15"},{count:100,date:"2012-05-16"},{count:100,date:"2012-05-17"},{count:100,date:"2012-05-18"},{count:100,date:"2012-05-19"},{count:100,date:"2012-05-20"},{count:100,date:"2012-05-21"},{count:100,date:"2012-05-22"},{count:100,date:"2012-05-23"},{count:100,date:"2012-05-24"},{count:100,date:"2012-05-25"},{count:100,date:"2012-05-26"},{count:100,date:"2012-05-27"},{count:100,date:"2012-05-28"},{count:100,date:"2012-05-29"},{count:100,date:"2012-05-30"},{count:100,date:"2012-05-31"},{count:100,date:"2012-06-01"},{count:100,date:"2012-06-02"},{count:100,date:"2012-06-03"},{count:100,date:"2012-06-04"},{count:100,date:"2012-06-05"},{count:100,date:"2012-06-06"},{count:100,date:"2012-06-07"},{count:100,date:"2012-06-08"},{count:100,date:"2012-06-09"},{count:100,date:"2012-06-10"},{count:100,date:"2012-06-11"},{count:100,date:"2012-06-12"},{count:100,date:"2012-06-13"},{count:100,date:"2012-06-14"},{count:100,date:"2012-06-15"},{count:100,date:"2012-06-16"},{count:100,date:"2012-06-17"},{count:100,date:"2012-06-18"},{count:100,date:"2012-06-19"},{count:100,date:"2012-06-20"},{count:100,date:"2012-06-21"},{count:100,date:"2012-06-22"},{count:100,date:"2012-06-23"},{count:100,date:"2012-06-24"},{count:100,date:"2012-06-25"},{count:100,date:"2012-06-26"},{count:100,date:"2012-06-27"},{count:100,date:"2012-06-28"},{count:100,date:"2012-06-29"},{count:100,date:"2012-06-30"},{count:100,date:"2012-07-01"},{count:100,date:"2012-07-02"},{count:100,date:"2012-07-03"},{count:100,date:"2012-07-04"},{count:4,date:"2012-07-05"},{count:0,date:"2012-07-06"},{count:0,date:"2012-07-07"},{count:96,date:"2012-07-08"},{count:100,date:"2012-07-09"},{count:100,date:"2012-07-10"},{count:100,date:"2012-07-11"},{count:100,date:"2012-07-12"},{count:100,date:"2012-07-13"},{count:100,date:"2012-07-14"},{count:100,date:"2012-07-15"},{count:100,date:"2012-07-16"},{count:100,date:"2012-07-17"},{count:100,date:"2012-07-18"},{count:100,date:"2012-07-19"},{count:100,date:"2012-07-20"},{count:100,date:"2012-07-21"},{count:100,date:"2012-07-22"},{count:100,date:"2012-07-23"},{count:100,date:"2012-07-24"},{count:100,date:"2012-07-25"},{count:100,date:"2012-07-26"},{count:100,date:"2012-07-27"},{count:100,date:"2012-07-28"},{count:100,date:"2012-07-29"},{count:100,date:"2012-07-30"},{count:100,date:"2012-07-31"},{count:100,date:"2012-08-01"},{count:100,date:"2012-08-02"},{count:100,date:"2012-08-03"},{count:100,date:"2012-08-04"},{count:100,date:"2012-08-05"},{count:100,date:"2012-08-06"},{count:100,date:"2012-08-07"},{count:100,date:"2012-08-08"},{count:100,date:"2012-08-09"},{count:100,date:"2012-08-10"},{count:100,date:"2012-08-11"},{count:100,date:"2012-08-12"},{count:100,date:"2012-08-13"},{count:100,date:"2012-08-14"},{count:100,date:"2012-08-15"},{count:100,date:"2012-08-16"},{count:100,date:"2012-08-17"},{count:100,date:"2012-08-18"},{count:100,date:"2012-08-19"},{count:100,date:"2012-08-20"},{count:100,date:"2012-08-21"},{count:100,date:"2012-08-22"},{count:100,date:"2012-08-23"},{count:100,date:"2012-08-24"},{count:100,date:"2012-08-25"},{count:100,date:"2012-08-26"},{count:100,date:"2012-08-27"},{count:100,date:"2012-08-28"},{count:100,date:"2012-08-29"},{count:100,date:"2012-08-30"},{count:100,date:"2012-08-31"},{count:100,date:"2012-09-01"},{count:100,date:"2012-09-02"},{count:100,date:"2012-09-03"},{count:100,date:"2012-09-04"},{count:100,date:"2012-09-05"},{count:100,date:"2012-09-06"},{count:100,date:"2012-09-07"},{count:100,date:"2012-09-08"},{count:100,date:"2012-09-09"},{count:100,date:"2012-09-10"},{count:100,date:"2012-09-11"},{count:100,date:"2012-09-12"},{count:100,date:"2012-09-13"},{count:100,date:"2012-09-14"},{count:100,date:"2012-09-15"},{count:100,date:"2012-09-16"},{count:100,date:"2012-09-17"},{count:100,date:"2012-09-18"},{count:100,date:"2012-09-19"},{count:100,date:"2012-09-20"},{count:100,date:"2012-09-21"},{count:100,date:"2012-09-22"},{count:100,date:"2012-09-23"},{count:100,date:"2012-09-24"},{count:100,date:"2012-09-25"},{count:100,date:"2012-09-26"},{count:100,date:"2012-09-27"},{count:100,date:"2012-09-28"},{count:100,date:"2012-09-29"},{count:100,date:"2012-09-30"},{count:100,date:"2012-10-01"},{count:100,date:"2012-10-02"},{count:100,date:"2012-10-03"},{count:100,date:"2012-10-04"},{count:100,date:"2012-10-05"},{count:100,date:"2012-10-06"},{count:100,date:"2012-10-07"},{count:100,date:"2012-10-08"},{count:100,date:"2012-10-09"},{count:100,date:"2012-10-10"},{count:100,date:"2012-10-11"},{count:100,date:"2012-10-12"},{count:100,date:"2012-10-13"},{count:100,date:"2012-10-14"},{count:100,date:"2012-10-15"},{count:100,date:"2012-10-16"},{count:4,date:"2012-10-17"},{count:96,date:"2012-10-18"},{count:100,date:"2012-10-19"},{count:100,date:"2012-10-20"},{count:100,date:"2012-10-21"},{count:100,date:"2012-10-22"},{count:100,date:"2012-10-23"},{count:100,date:"2012-10-24"},{count:100,date:"2012-10-25"},{count:100,date:"2012-10-26"},{count:100,date:"2012-10-27"},{count:100,date:"2012-10-28"},{count:100,date:"2012-10-29"},{count:100,date:"2012-10-30"},{count:100,date:"2012-10-31"},{count:100,date:"2012-11-01"},{count:100,date:"2012-11-02"},{count:100,date:"2012-11-03"},{count:100,date:"2012-11-04"},{count:100,date:"2012-11-05"},{count:100,date:"2012-11-06"},{count:100,date:"2012-11-07"},{count:100,date:"2012-11-08"},{count:100,date:"2012-11-09"},{count:100,date:"2012-11-10"},{count:100,date:"2012-11-11"},{count:100,date:"2012-11-12"},{count:100,date:"2012-11-13"},{count:100,date:"2012-11-14"},{count:100,date:"2012-11-15"},{count:100,date:"2012-11-16"},{count:100,date:"2012-11-17"},{count:100,date:"2012-11-18"},{count:100,date:"2012-11-19"},{count:100,date:"2012-11-20"},{count:100,date:"2012-11-21"},{count:100,date:"2012-11-22"},{count:100,date:"2012-11-23"},{count:100,date:"2012-11-24"},{count:100,date:"2012-11-25"},{count:100,date:"2012-11-26"},{count:100,date:"2012-11-27"},{count:100,date:"2012-11-28"},{count:100,date:"2012-11-29"},{count:100,date:"2012-11-30"},{count:100,date:"2012-12-01"},{count:100,date:"2012-12-02"},{count:100,date:"2012-12-03"},{count:100,date:"2012-12-04"},{count:100,date:"2012-12-05"},{count:100,date:"2012-12-06"},{count:100,date:"2012-12-07"},{count:100,date:"2012-12-08"},{count:100,date:"2012-12-09"},{count:100,date:"2012-12-10"},{count:100,date:"2012-12-11"},{count:100,date:"2012-12-12"},{count:100,date:"2012-12-13"},{count:100,date:"2012-12-14"},{count:100,date:"2012-12-15"},{count:100,date:"2012-12-16"},{count:100,date:"2012-12-17"},{count:100,date:"2012-12-18"},{count:100,date:"2012-12-19"},{count:100,date:"2012-12-20"},{count:100,date:"2012-12-21"},{count:100,date:"2012-12-22"},{count:100,date:"2012-12-23"},{count:100,date:"2012-12-24"},{count:100,date:"2012-12-25"},{count:100,date:"2012-12-26"},{count:100,date:"2012-12-27"},{count:100,date:"2012-12-28"},{count:100,date:"2012-12-29"},{count:100,date:"2012-12-30"},{count:100,date:"2012-12-31"},{count:100,date:"2013-01-01"},{count:100,date:"2013-01-02"},{count:100,date:"2013-01-03"},{count:100,date:"2013-01-04"},{count:100,date:"2013-01-05"},{count:100,date:"2013-01-06"},{count:100,date:"2013-01-07"},{count:100,date:"2013-01-08"},{count:100,date:"2013-01-09"},{count:100,date:"2013-01-10"},{count:100,date:"2013-01-11"},{count:100,date:"2013-01-12"},{count:100,date:"2013-01-13"},{count:100,date:"2013-01-14"},{count:100,date:"2013-01-15"},{count:100,date:"2013-01-16"},{count:100,date:"2013-01-17"},{count:100,date:"2013-01-18"},{count:100,date:"2013-01-19"},{count:100,date:"2013-01-20"},{count:100,date:"2013-01-21"},{count:100,date:"2013-01-22"},{count:100,date:"2013-01-23"},{count:100,date:"2013-01-24"},{count:100,date:"2013-01-25"},{count:100,date:"2013-01-26"},{count:100,date:"2013-01-27"},{count:100,date:"2013-01-28"},{count:100,date:"2013-01-29"},{count:100,date:"2013-01-30"},{count:100,date:"2013-01-31"},{count:100,date:"2013-02-01"},{count:100,date:"2013-02-02"},{count:100,date:"2013-02-03"},{count:100,date:"2013-02-04"},{count:100,date:"2013-02-05"},{count:100,date:"2013-02-06"},{count:100,date:"2013-02-07"},{count:100,date:"2013-02-08"},{count:100,date:"2013-02-09"},{count:100,date:"2013-02-10"},{count:100,date:"2013-02-11"},{count:100,date:"2013-02-12"},{count:0,date:"2013-02-13"},{count:100,date:"2013-02-14"},{count:100,date:"2013-02-15"},{count:100,date:"2013-02-16"},{count:100,date:"2013-02-17"},{count:100,date:"2013-02-18"},{count:100,date:"2013-02-19"},{count:100,date:"2013-02-20"},{count:100,date:"2013-02-21"},{count:100,date:"2013-02-22"},{count:100,date:"2013-02-23"},{count:100,date:"2013-02-24"},{count:100,date:"2013-02-25"},{count:100,date:"2013-02-26"},{count:100,date:"2013-02-27"},{count:100,date:"2013-02-28"},{count:100,date:"2013-03-01"},{count:100,date:"2013-03-02"},{count:100,date:"2013-03-03"},{count:100,date:"2013-03-04"},{count:100,date:"2013-03-05"},{count:100,date:"2013-03-06"},{count:100,date:"2013-03-07"},{count:100,date:"2013-03-08"},{count:100,date:"2013-03-09"},{count:100,date:"2013-03-10"},{count:100,date:"2013-03-11"},{count:100,date:"2013-03-12"},{count:100,date:"2013-03-13"},{count:100,date:"2013-03-14"},{count:100,date:"2013-03-15"},{count:100,date:"2013-03-16"},{count:100,date:"2013-03-17"},{count:100,date:"2013-03-18"},{count:100,date:"2013-03-19"},{count:100,date:"2013-03-20"},{count:100,date:"2013-03-21"},{count:100,date:"2013-03-22"},{count:100,date:"2013-03-23"},{count:100,date:"2013-03-24"},{count:100,date:"2013-03-25"},{count:100,date:"2013-03-26"},{count:100,date:"2013-03-27"},{count:100,date:"2013-03-28"},{count:100,date:"2013-03-29"},{count:100,date:"2013-03-30"},{count:96,date:"2013-03-31"},{count:100,date:"2013-04-01"},{count:100,date:"2013-04-02"},{count:100,date:"2013-04-03"},{count:100,date:"2013-04-04"},{count:100,date:"2013-04-05"},{count:100,date:"2013-04-06"},{count:100,date:"2013-04-07"},{count:100,date:"2013-04-08"},{count:100,date:"2013-04-09"},{count:100,date:"2013-04-10"},{count:100,date:"2013-04-11"},{count:100,date:"2013-04-12"},{count:100,date:"2013-04-13"},{count:100,date:"2013-04-14"},{count:100,date:"2013-04-15"},{count:100,date:"2013-04-16"},{count:100,date:"2013-04-17"},{count:100,date:"2013-04-18"},{count:100,date:"2013-04-19"},{count:100,date:"2013-04-20"},{count:100,date:"2013-04-21"},{count:100,date:"2013-04-22"},{count:100,date:"2013-04-23"},{count:100,date:"2013-04-24"},{count:100,date:"2013-04-25"},{count:100,date:"2013-04-26"},{count:100,date:"2013-04-27"},{count:100,date:"2013-04-28"},{count:100,date:"2013-04-29"},{count:100,date:"2013-04-30"},{count:100,date:"2013-05-01"},{count:100,date:"2013-05-02"},{count:100,date:"2013-05-03"},{count:100,date:"2013-05-04"},{count:100,date:"2013-05-05"},{count:100,date:"2013-05-06"},{count:100,date:"2013-05-07"},{count:100,date:"2013-05-08"},{count:100,date:"2013-05-09"},{count:100,date:"2013-05-10"},{count:100,date:"2013-05-11"},{count:100,date:"2013-05-12"},{count:100,date:"2013-05-13"},{count:100,date:"2013-05-14"},{count:100,date:"2013-05-15"},{count:100,date:"2013-05-16"},{count:100,date:"2013-05-17"},{count:100,date:"2013-05-18"},{count:100,date:"2013-05-19"},{count:100,date:"2013-05-20"},{count:100,date:"2013-05-21"},{count:100,date:"2013-05-22"},{count:100,date:"2013-05-23"},{count:100,date:"2013-05-24"},{count:100,date:"2013-05-25"},{count:100,date:"2013-05-26"},{count:100,date:"2013-05-27"},{count:100,date:"2013-05-28"},{count:100,date:"2013-05-29"},{count:100,date:"2013-05-30"},{count:100,date:"2013-05-31"},{count:100,date:"2013-06-01"},{count:100,date:"2013-06-02"},{count:100,date:"2013-06-03"},{count:100,date:"2013-06-04"},{count:100,date:"2013-06-05"},{count:100,date:"2013-06-06"},{count:100,date:"2013-06-07"},{count:100,date:"2013-06-08"},{count:100,date:"2013-06-09"},{count:100,date:"2013-06-10"},{count:100,date:"2013-06-11"},{count:100,date:"2013-06-12"},{count:100,date:"2013-06-13"},{count:100,date:"2013-06-14"},{count:100,date:"2013-06-15"},{count:100,date:"2013-06-16"},{count:100,date:"2013-06-17"},{count:100,date:"2013-06-18"},{count:100,date:"2013-06-19"},{count:100,date:"2013-06-20"},{count:100,date:"2013-06-21"},{count:100,date:"2013-06-22"},{count:100,date:"2013-06-23"},{count:100,date:"2013-06-24"},{count:100,date:"2013-06-25"},{count:100,date:"2013-06-26"},{count:100,date:"2013-06-27"},{count:100,date:"2013-06-28"},{count:100,date:"2013-06-29"},{count:100,date:"2013-06-30"},{count:4,date:"2013-07-01"},{count:0,date:"2013-07-02"},{count:0,date:"2013-07-03"},{count:96,date:"2013-07-04"},{count:100,date:"2013-07-05"},{count:100,date:"2013-07-06"},{count:100,date:"2013-07-07"},{count:100,date:"2013-07-08"},{count:100,date:"2013-07-09"},{count:100,date:"2013-07-10"},{count:100,date:"2013-07-11"},{count:100,date:"2013-07-12"},{count:4,date:"2013-07-13"},{count:96,date:"2013-07-14"},{count:4,date:"2013-07-15"},{count:0,date:"2013-07-16"},{count:0,date:"2013-07-17"},{count:0,date:"2013-07-18"},{count:0,date:"2013-07-19"},{count:0,date:"2013-07-20"},{count:0,date:"2013-07-21"},{count:0,date:"2013-07-22"},{count:0,date:"2013-07-23"},{count:0,date:"2013-07-24"},{count:0,date:"2013-07-25"},{count:0,date:"2013-07-26"},{count:0,date:"2013-07-27"},{count:0,date:"2013-07-28"},{count:0,date:"2013-07-29"},{count:0,date:"2013-07-30"},{count:0,date:"2013-07-31"},{count:0,date:"2013-08-01"},{count:0,date:"2013-08-02"},{count:96,date:"2013-08-03"},{count:100,date:"2013-08-04"},{count:100,date:"2013-08-05"},{count:100,date:"2013-08-06"},{count:100,date:"2013-08-07"},{count:100,date:"2013-08-08"},{count:100,date:"2013-08-09"},{count:100,date:"2013-08-10"},{count:100,date:"2013-08-11"},{count:100,date:"2013-08-12"},{count:100,date:"2013-08-13"},{count:100,date:"2013-08-14"},{count:100,date:"2013-08-15"},{count:100,date:"2013-08-16"},{count:100,date:"2013-08-17"},{count:100,date:"2013-08-18"},{count:100,date:"2013-08-19"},{count:4,date:"2013-08-20"},{count:96,date:"2013-08-21"},{count:100,date:"2013-08-22"},{count:100,date:"2013-08-23"},{count:100,date:"2013-08-24"},{count:100,date:"2013-08-25"},{count:100,date:"2013-08-26"},{count:100,date:"2013-08-27"},{count:100,date:"2013-08-28"},{count:100,date:"2013-08-29"},{count:100,date:"2013-08-30"},{count:100,date:"2013-08-31"},{count:100,date:"2013-09-01"},{count:100,date:"2013-09-02"},{count:100,date:"2013-09-03"},{count:100,date:"2013-09-04"},{count:100,date:"2013-09-05"},{count:100,date:"2013-09-06"},{count:100,date:"2013-09-07"},{count:100,date:"2013-09-08"},{count:100,date:"2013-09-09"},{count:100,date:"2013-09-10"},{count:100,date:"2013-09-11"},{count:100,date:"2013-09-12"},{count:100,date:"2013-09-13"},{count:100,date:"2013-09-14"},{count:100,date:"2013-09-15"},{count:100,date:"2013-09-16"},{count:4,date:"2013-09-17"},{count:96,date:"2013-09-18"},{count:4,date:"2013-09-19"},{count:0,date:"2013-09-20"},{count:96,date:"2013-09-21"},{count:4,date:"2013-09-22"},{count:96,date:"2013-09-23"},{count:100,date:"2013-09-24"},{count:100,date:"2013-09-25"},{count:100,date:"2013-09-26"},{count:100,date:"2013-09-27"},{count:100,date:"2013-09-28"},{count:100,date:"2013-09-29"},{count:100,date:"2013-09-30"},{count:100,date:"2013-10-01"},{count:100,date:"2013-10-02"},{count:100,date:"2013-10-03"},{count:100,date:"2013-10-04"},{count:100,date:"2013-10-05"},{count:100,date:"2013-10-06"},{count:100,date:"2013-10-07"},{count:100,date:"2013-10-08"},{count:100,date:"2013-10-09"},{count:100,date:"2013-10-10"},{count:100,date:"2013-10-11"},{count:100,date:"2013-10-12"},{count:100,date:"2013-10-13"},{count:100,date:"2013-10-14"},{count:100,date:"2013-10-15"},{count:100,date:"2013-10-16"},{count:100,date:"2013-10-17"},{count:100,date:"2013-10-18"},{count:100,date:"2013-10-19"},{count:100,date:"2013-10-20"},{count:100,date:"2013-10-21"},{count:100,date:"2013-10-22"},{count:100,date:"2013-10-23"},{count:100,date:"2013-10-24"},{count:100,date:"2013-10-25"},{count:100,date:"2013-10-26"},{count:100,date:"2013-10-27"},{count:100,date:"2013-10-28"},{count:100,date:"2013-10-29"},{count:100,date:"2013-10-30"},{count:100,date:"2013-10-31"},{count:100,date:"2013-11-01"},{count:100,date:"2013-11-02"},{count:100,date:"2013-11-03"},{count:100,date:"2013-11-04"},{count:100,date:"2013-11-05"},{count:100,date:"2013-11-06"},{count:100,date:"2013-11-07"},{count:100,date:"2013-11-08"},{count:100,date:"2013-11-09"},{count:100,date:"2013-11-10"},{count:100,date:"2013-11-11"},{count:100,date:"2013-11-12"},{count:100,date:"2013-11-13"},{count:0,date:"2013-11-14"},{count:0,date:"2013-11-15"},{count:100,date:"2013-11-16"},{count:100,date:"2013-11-17"},{count:100,date:"2013-11-18"},{count:100,date:"2013-11-19"},{count:0,date:"2013-11-20"},{count:0,date:"2013-11-21"},{count:100,date:"2013-11-22"},{count:0,date:"2013-11-23"},{count:100,date:"2013-11-24"},{count:100,date:"2013-11-25"},{count:100,date:"2013-11-26"},{count:100,date:"2013-11-27"},{count:100,date:"2013-11-28"},{count:100,date:"2013-11-29"},{count:100,date:"2013-11-30"},{count:100,date:"2013-12-01"},{count:100,date:"2013-12-02"},{count:100,date:"2013-12-03"},{count:100,date:"2013-12-04"},{count:100,date:"2013-12-05"},{count:100,date:"2013-12-06"},{count:100,date:"2013-12-07"},{count:100,date:"2013-12-08"},{count:100,date:"2013-12-09"},{count:100,date:"2013-12-10"},{count:100,date:"2013-12-11"},{count:100,date:"2013-12-12"},{count:100,date:"2013-12-13"},{count:100,date:"2013-12-14"},{count:100,date:"2013-12-15"},{count:100,date:"2013-12-16"},{count:100,date:"2013-12-17"},{count:100,date:"2013-12-18"},{count:100,date:"2013-12-19"},{count:100,date:"2013-12-20"},{count:100,date:"2013-12-21"},{count:100,date:"2013-12-22"},{count:100,date:"2013-12-23"},{count:100,date:"2013-12-24"},{count:100,date:"2013-12-25"},{count:100,date:"2013-12-26"},{count:100,date:"2013-12-27"},{count:100,date:"2013-12-28"},{count:100,date:"2013-12-29"},{count:100,date:"2013-12-30"},{count:100,date:"2013-12-31"},{count:100,date:"2014-01-01"},{count:100,date:"2014-01-02"},{count:100,date:"2014-01-03"},{count:100,date:"2014-01-04"},{count:100,date:"2014-01-05"},{count:100,date:"2014-01-06"},{count:100,date:"2014-01-07"},{count:100,date:"2014-01-08"},{count:100,date:"2014-01-09"},{count:100,date:"2014-01-10"},{count:100,date:"2014-01-11"},{count:100,date:"2014-01-12"},{count:100,date:"2014-01-13"},{count:100,date:"2014-01-14"},{count:100,date:"2014-01-15"},{count:100,date:"2014-01-16"},{count:100,date:"2014-01-17"},{count:100,date:"2014-01-18"},{count:100,date:"2014-01-19"},{count:100,date:"2014-01-20"},{count:100,date:"2014-01-21"},{count:100,date:"2014-01-22"},{count:100,date:"2014-01-23"},{count:100,date:"2014-01-24"},{count:100,date:"2014-01-25"},{count:100,date:"2014-01-26"},{count:100,date:"2014-01-27"},{count:100,date:"2014-01-28"},{count:100,date:"2014-01-29"},{count:100,date:"2014-01-30"},{count:100,date:"2014-01-31"},{count:100,date:"2014-02-01"},{count:100,date:"2014-02-02"},{count:100,date:"2014-02-03"},{count:100,date:"2014-02-04"},{count:100,date:"2014-02-05"},{count:100,date:"2014-02-06"},{count:100,date:"2014-02-07"},{count:100,date:"2014-02-08"},{count:100,date:"2014-02-09"},{count:100,date:"2014-02-10"},{count:100,date:"2014-02-11"},{count:100,date:"2014-02-12"},{count:100,date:"2014-02-13"},{count:100,date:"2014-02-14"},{count:100,date:"2014-02-15"},{count:100,date:"2014-02-16"},{count:100,date:"2014-02-17"},{count:100,date:"2014-02-18"},{count:100,date:"2014-02-19"},{count:100,date:"2014-02-20"},{count:100,date:"2014-02-21"},{count:100,date:"2014-02-22"},{count:100,date:"2014-02-23"},{count:100,date:"2014-02-24"},{count:100,date:"2014-02-25"},{count:100,date:"2014-02-26"},{count:100,date:"2014-02-27"},{count:100,date:"2014-02-28"},{count:100,date:"2014-03-01"},{count:100,date:"2014-03-02"},{count:100,date:"2014-03-03"},{count:100,date:"2014-03-04"},{count:100,date:"2014-03-05"},{count:100,date:"2014-03-06"},{count:100,date:"2014-03-07"},{count:100,date:"2014-03-08"},{count:100,date:"2014-03-09"},{count:100,date:"2014-03-10"},{count:100,date:"2014-03-11"},{count:100,date:"2014-03-12"},{count:100,date:"2014-03-13"},{count:100,date:"2014-03-14"},{count:100,date:"2014-03-15"},{count:100,date:"2014-03-16"},{count:100,date:"2014-03-17"},{count:100,date:"2014-03-18"},{count:100,date:"2014-03-19"},{count:100,date:"2014-03-20"},{count:0,date:"2014-03-21"},{count:100,date:"2014-03-22"},{count:100,date:"2014-03-23"},{count:100,date:"2014-03-24"},{count:100,date:"2014-03-25"},{count:100,date:"2014-03-26"},{count:100,date:"2014-03-27"},{count:100,date:"2014-03-28"},{count:100,date:"2014-03-29"},{count:96,date:"2014-03-30"},{count:100,date:"2014-03-31"},{count:100,date:"2014-04-01"},{count:100,date:"2014-04-02"},{count:100,date:"2014-04-03"},{count:100,date:"2014-04-04"},{count:100,date:"2014-04-05"},{count:100,date:"2014-04-06"},{count:100,date:"2014-04-07"},{count:100,date:"2014-04-08"},{count:100,date:"2014-04-09"},{count:100,date:"2014-04-10"},{count:100,date:"2014-04-11"},{count:100,date:"2014-04-12"},{count:100,date:"2014-04-13"},{count:100,date:"2014-04-14"},{count:100,date:"2014-04-15"},{count:100,date:"2014-04-16"},{count:100,date:"2014-04-17"},{count:100,date:"2014-04-18"},{count:100,date:"2014-04-19"},{count:100,date:"2014-04-20"},{count:100,date:"2014-04-21"},{count:100,date:"2014-04-22"},{count:100,date:"2014-04-23"},{count:100,date:"2014-04-24"},{count:100,date:"2014-04-25"},{count:100,date:"2014-04-26"},{count:100,date:"2014-04-27"},{count:100,date:"2014-04-28"},{count:100,date:"2014-04-29"},{count:100,date:"2014-04-30"},{count:100,date:"2014-05-01"},{count:100,date:"2014-05-02"},{count:100,date:"2014-05-03"},{count:100,date:"2014-05-04"},{count:100,date:"2014-05-05"},{count:100,date:"2014-05-06"},{count:100,date:"2014-05-07"},{count:100,date:"2014-05-08"},{count:100,date:"2014-05-09"},{count:100,date:"2014-05-10"},{count:100,date:"2014-05-11"},{count:100,date:"2014-05-12"},{count:100,date:"2014-05-13"},{count:100,date:"2014-05-14"},{count:100,date:"2014-05-15"},{count:100,date:"2014-05-16"},{count:100,date:"2014-05-17"},{count:100,date:"2014-05-18"},{count:100,date:"2014-05-19"},{count:100,date:"2014-05-20"},{count:100,date:"2014-05-21"},{count:100,date:"2014-05-22"},{count:100,date:"2014-05-23"},{count:100,date:"2014-05-24"},{count:100,date:"2014-05-25"},{count:100,date:"2014-05-26"},{count:100,date:"2014-05-27"},{count:100,date:"2014-05-28"},{count:100,date:"2014-05-29"},{count:100,date:"2014-05-30"},{count:100,date:"2014-05-31"},{count:100,date:"2014-06-01"},{count:100,date:"2014-06-02"},{count:100,date:"2014-06-03"},{count:100,date:"2014-06-04"},{count:100,date:"2014-06-05"},{count:100,date:"2014-06-06"},{count:100,date:"2014-06-07"},{count:100,date:"2014-06-08"},{count:100,date:"2014-06-09"},{count:100,date:"2014-06-10"},{count:100,date:"2014-06-11"},{count:100,date:"2014-06-12"},{count:100,date:"2014-06-13"},{count:100,date:"2014-06-14"},{count:100,date:"2014-06-15"},{count:100,date:"2014-06-16"},{count:100,date:"2014-06-17"},{count:100,date:"2014-06-18"},{count:100,date:"2014-06-19"},{count:100,date:"2014-06-20"},{count:100,date:"2014-06-21"},{count:100,date:"2014-06-22"},{count:100,date:"2014-06-23"},{count:100,date:"2014-06-24"},{count:100,date:"2014-06-25"},{count:100,date:"2014-06-26"},{count:100,date:"2014-06-27"},{count:100,date:"2014-06-28"},{count:100,date:"2014-06-29"},{count:100,date:"2014-06-30"},{count:100,date:"2014-07-01"},{count:100,date:"2014-07-02"},{count:100,date:"2014-07-03"},{count:100,date:"2014-07-04"},{count:100,date:"2014-07-05"},{count:100,date:"2014-07-06"},{count:100,date:"2014-07-07"},{count:100,date:"2014-07-08"},{count:100,date:"2014-07-09"},{count:100,date:"2014-07-10"},{count:100,date:"2014-07-11"},{count:100,date:"2014-07-12"},{count:100,date:"2014-07-13"},{count:100,date:"2014-07-14"},{count:100,date:"2014-07-15"},{count:100,date:"2014-07-16"},{count:100,date:"2014-07-17"},{count:100,date:"2014-07-18"},{count:100,date:"2014-07-19"},{count:100,date:"2014-07-20"},{count:100,date:"2014-07-21"},{count:100,date:"2014-07-22"},{count:100,date:"2014-07-23"},{count:100,date:"2014-07-24"},{count:100,date:"2014-07-25"},{count:100,date:"2014-07-26"},{count:100,date:"2014-07-27"},{count:100,date:"2014-07-28"},{count:100,date:"2014-07-29"},{count:100,date:"2014-07-30"},{count:100,date:"2014-07-31"},{count:100,date:"2014-08-01"},{count:100,date:"2014-08-02"},{count:100,date:"2014-08-03"},{count:100,date:"2014-08-04"},{count:100,date:"2014-08-05"},{count:100,date:"2014-08-06"},{count:100,date:"2014-08-07"},{count:100,date:"2014-08-08"},{count:100,date:"2014-08-09"},{count:100,date:"2014-08-10"},{count:100,date:"2014-08-11"},{count:100,date:"2014-08-12"},{count:100,date:"2014-08-13"},{count:100,date:"2014-08-14"},{count:100,date:"2014-08-15"},{count:100,date:"2014-08-16"},{count:100,date:"2014-08-17"},{count:100,date:"2014-08-18"},{count:100,date:"2014-08-19"},{count:100,date:"2014-08-20"},{count:100,date:"2014-08-21"},{count:100,date:"2014-08-22"},{count:100,date:"2014-08-23"}]      `

The result (please note I changed the default colour for the no-data to red). 2012 should be full with green rather than red.

![image](https://user-images.githubusercontent.com/16774169/131844916-1b2ce60d-865b-443e-af61-0f6c3eef6780.png)

**Comment by SeBassTian23** [comment]
Hm,

I took a look at the example you provided. Just to be sure I just downloaded the repo and used the files from the dist folder. I also used the custom colors you used. This is the result that I get:

<img width="953" alt="Screen Shot" src="https://user-images.githubusercontent.com/6181737/131855839-ca0d40cd-c843-4316-a54c-3d96c5c75f53.png">

**Comment by albertogtello** [comment]
Hi Sebastian, 
What you showed is exactly what I am expecting, so that means the mistake is on me now. 
Are these the files to use:
![image](https://user-images.githubusercontent.com/84132809/131864277-40c2fded-4cf1-400a-9ee8-97296f2e1c8b.png)
 I am using the large version of them.
Cheers.

**Comment by SeBassTian23** [comment]
Okay, let's figure this one out... I wonder if it is a css issue? Please find the styles I used below. I used the same files (non minified version). I was not 100% sure if the click event is the issue, but I checked and on my end it seems, it is not.

```css
.ch-day, .custom-0 {
	background-color: #FB0006 !important;
}
.ch-day.is-outside-month {
	background-color: transparent !important;
}
.custom-1 {
	background-color: #FD940A !important;
}
.custom-2 {
	background-color: #FFFF0B !important;
}
.custom-3 {
	background-color: #22FF08 !important;
}
.custom-4 {
	background-color: #387C03 !important;
}
```

**Comment by AlbertoMCS** [comment]
It gets more interesting: the minified js works, the other one does not.

**Comment by SeBassTian23** [comment]
hm, that is strange indeed. I have no idea why this would happen. I will investigate. what os/browser are you using, perhaps that is giving us a clue?

**Comment by AlbertoMCS** [comment]
Hi Sebastian,
I am using windows 10 and this browser:
[cid:ca4698c4-8003-4234-a331-3e042d29694b]

Cheers.

________________________________
